// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

// Generated by scripts/credit-vectors.mjs from docs/erc-8004-credit/vectors.json: do not edit by hand.
// The ERC-8004 credit profile's leaf hash and Merkle proofs, checked with OpenZeppelin's MerkleProof, so a contract can
// prove one loan of a statement on chain (docs/ERC-8004-CREDIT.md).
import {Test} from "forge-std/Test.sol";
import {MerkleProof} from "@openzeppelin/contracts/utils/cryptography/MerkleProof.sol";

contract CreditProfileVectorsTest is Test {
    uint256 constant CHAIN_ID = 1;
    address constant LENDER = 0x00000000000000000000000000000000000c0ffe;
    uint256 constant AGENT = 9007199254740993;
    bytes32 constant ROOT = 0xa02307154090a55a259144c9782a14786e565773f297609af9b4b42f0abe2ebc;

    function _leaf(
        uint256 loanId,
        uint256 amount,
        uint64 dueAt,
        uint64 closedAt,
        uint8 outcome,
        bytes32 txHash,
        uint32 logIndex
    ) internal pure returns (bytes32) {
        return keccak256(
            bytes.concat(
                keccak256(
                    abi.encode(CHAIN_ID, LENDER, AGENT, loanId, amount, dueAt, closedAt, outcome, txHash, logIndex)
                )
            )
        );
    }

    function _leaves() internal pure returns (bytes32[] memory h) {
        h = new bytes32[](5);
        h[0] = _leaf(
            1,
            5000000,
            1800000000,
            1799990000,
            1,
            bytes32(0x00000000000000000000000000000000000000000000000000000000000000a1),
            3
        );
        h[1] = _leaf(
            2,
            12500000,
            1800100000,
            1800150000,
            2,
            bytes32(0x00000000000000000000000000000000000000000000000000000000000000a2),
            0
        );
        h[2] = _leaf(
            18446744073709551617,
            250000000,
            1800200000,
            1800190000,
            1,
            bytes32(0x00000000000000000000000000000000000000000000000000000000000000a3),
            7
        );
        h[3] = _leaf(
            4,
            7000000,
            1800300000,
            1800400000,
            3,
            bytes32(0x00000000000000000000000000000000000000000000000000000000000000a4),
            1
        );
        h[4] = _leaf(
            5,
            1000000,
            1800500000,
            1800450000,
            1,
            bytes32(0x00000000000000000000000000000000000000000000000000000000000000a5),
            2
        );
    }

    function test_leafHashes() public pure {
        bytes32[] memory h = _leaves();
        assertEq(h[0], 0x8138152b80c1195427b593cf69340ce22ae1d3196137f3278d4799541fb0da53);
        assertEq(h[1], 0x6f562a5c681dda041b35f809baa01acc82743957c79e79eb463730c6e88d71ab);
        assertEq(h[2], 0x8d99d3b2bc9c25d27e72beb869b3708f0987026a7813e81ac303468a4479a4c6);
        assertEq(h[3], 0xfb27fbd392a561ead296054c285de563d62aec521bc47ae171f487bc6b0b5c95);
        assertEq(h[4], 0x5d8d06f3afdfa7a6de691c001dbc4ab4c0fc4c4aa724764aa50f5b20569f3b93);
    }

    function test_proofs() public pure {
        bytes32[] memory h = _leaves();
        bytes32[] memory p0 = new bytes32[](3);
        p0[0] = bytes32(0x6f562a5c681dda041b35f809baa01acc82743957c79e79eb463730c6e88d71ab);
        p0[1] = bytes32(0x0c1781bce78c5ca97ab2fb61b16100948cf1f099340df75f9e9ebe848a34c659);
        p0[2] = bytes32(0x5d8d06f3afdfa7a6de691c001dbc4ab4c0fc4c4aa724764aa50f5b20569f3b93);
        assertTrue(MerkleProof.verify(p0, ROOT, h[0]), "proof 0");
        bytes32[] memory p1 = new bytes32[](3);
        p1[0] = bytes32(0x8138152b80c1195427b593cf69340ce22ae1d3196137f3278d4799541fb0da53);
        p1[1] = bytes32(0x0c1781bce78c5ca97ab2fb61b16100948cf1f099340df75f9e9ebe848a34c659);
        p1[2] = bytes32(0x5d8d06f3afdfa7a6de691c001dbc4ab4c0fc4c4aa724764aa50f5b20569f3b93);
        assertTrue(MerkleProof.verify(p1, ROOT, h[1]), "proof 1");
        bytes32[] memory p2 = new bytes32[](3);
        p2[0] = bytes32(0xfb27fbd392a561ead296054c285de563d62aec521bc47ae171f487bc6b0b5c95);
        p2[1] = bytes32(0x877793f34c5d4d0fa17dc6c76daf576bd07d3f55fe757a6ab766c2502a02934d);
        p2[2] = bytes32(0x5d8d06f3afdfa7a6de691c001dbc4ab4c0fc4c4aa724764aa50f5b20569f3b93);
        assertTrue(MerkleProof.verify(p2, ROOT, h[2]), "proof 2");
        bytes32[] memory p3 = new bytes32[](3);
        p3[0] = bytes32(0x8d99d3b2bc9c25d27e72beb869b3708f0987026a7813e81ac303468a4479a4c6);
        p3[1] = bytes32(0x877793f34c5d4d0fa17dc6c76daf576bd07d3f55fe757a6ab766c2502a02934d);
        p3[2] = bytes32(0x5d8d06f3afdfa7a6de691c001dbc4ab4c0fc4c4aa724764aa50f5b20569f3b93);
        assertTrue(MerkleProof.verify(p3, ROOT, h[3]), "proof 3");
        bytes32[] memory p4 = new bytes32[](1);
        p4[0] = bytes32(0xe5d370379a9215a019e0efd61ccf044e014ff1d2305797486ea9b0c87ea54859);
        assertTrue(MerkleProof.verify(p4, ROOT, h[4]), "proof 4");
    }

    function test_tamperedLeafFails() public pure {
        bytes32[] memory h = _leaves();
        bytes32[] memory p0 = new bytes32[](3);
        p0[0] = bytes32(0x6f562a5c681dda041b35f809baa01acc82743957c79e79eb463730c6e88d71ab);
        p0[1] = bytes32(0x0c1781bce78c5ca97ab2fb61b16100948cf1f099340df75f9e9ebe848a34c659);
        p0[2] = bytes32(0x5d8d06f3afdfa7a6de691c001dbc4ab4c0fc4c4aa724764aa50f5b20569f3b93);
        // the same loan claimed as repaid on time with a larger amount
        bytes32 forged = _leaf(
            1,
            50000000,
            1800000000,
            1799990000,
            1,
            bytes32(0x00000000000000000000000000000000000000000000000000000000000000a1),
            3
        );
        assertTrue(forged != h[0]);
        assertFalse(MerkleProof.verify(p0, ROOT, forged));
    }
}
